run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - interfacer
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - goimports
    - maligned
    - misspell
    - lll
    - unparam
    - nakedret
    - prealloc
    - scopelint
    - gocritic

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - dupl
    - path: cmd/
      linters:
        - lll
  max-issues-per-linter: 0
  max-same-issues: 0
